[phpm]
version = "8.2"

[phpmExtensions]
extensions = [ "pdo_mysql", "mysqli", "mbstring", "exif", "gd", "zip", "curl", "bcmath", "ctype", "fileinfo", "json", "tokenizer", "xml" ]

[phpm.startCmd]
cmd = "php artisan serve --host=0.0.0.0 --port=${PORT}"
